In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("C:/Users/nayan/Downloads/india job market analysis/india_job_market_2024_2026.csv")
df.head()

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024

In [4]:
df.shape

(5000, 17)

In [5]:
df.columns

Index(['Job_ID', 'Job_Title', 'Company', 'Company_Type', 'Industry', 'City',
       'Location_Tier', 'Experience_Level', 'Job_Type', 'Work_Mode',
       'Salary_LPA', 'Skills_Required', 'Education_Required', 'Openings',
       'Applicants', 'Company_Rating', 'Date_Posted'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Job_ID              5000 non-null   object
 1   Job_Title           5000 non-null   object
 2   Company             5000 non-null   object
 3   Company_Type        5000 non-null   object
 4   Industry            5000 non-null   object
 5   City                5000 non-null   object
 6   Location_Tier       5000 non-null   object
 7   Experience_Level    5000 non-null   object
 8   Job_Type            5000 non-null   object
 9   Work_Mode           5000 non-null   object
 10  Salary_LPA          5000 non-null   float64
 11  Skills_Required     5000 non-null   object
 12  Education_Required  5000 non-null   object
 13  Openings            5000 non-null   int64
 14  Applicants          5000 non-null   int64
 15  Company_Rating      5000 non-null   float64
 16  Date_Posted         5000 non-null   object
dtypes: float64(2), int64(2), object(13)
memory usage: 664.2+ KB

In [7]:
df.dtypes

Job_ID                 object
Job_Title              object
Company                object
Company_Type           object
Industry               object
City                   object
Location_Tier          object
Experience_Level       object
Job_Type               object
Work_Mode              object
Salary_LPA            float64
Skills_Required        object
Education_Required     object
Openings                int64
Applicants              int64
Company_Rating        float64
Date_Posted            object
dtype: object

In [8]:
df["Date_Posted"] = pd.to_datetime(df["Date_Posted"],format="%d-%m-%Y")

In [9]:
df["Date_Posted"].dtypes

dtype('<M8[ns]')

In [10]:
df["Date_Posted_Month"] = df["Date_Posted"].dt.month

In [11]:
df["Date_Posted_Year"] = df["Date_Posted"].dt.year

In [12]:
df.columns

Index(['Job_ID', 'Job_Title', 'Company', 'Company_Type', 'Industry', 'City',
       'Location_Tier', 'Experience_Level', 'Job_Type', 'Work_Mode',
       'Salary_LPA', 'Skills_Required', 'Education_Required', 'Openings',
       'Applicants', 'Company_Rating', 'Date_Posted', 'Date_Posted_Month',
       'Date_Posted_Year'],
      dtype='object')

In [13]:
df["Date_Posted"] = df["Date_Posted"].dt.strftime("%d-%m-%Y")

In [14]:
df.isnull().sum()

Job_ID                0
Job_Title             0
Company               0
Company_Type          0
Industry              0
City                  0
Location_Tier         0
Experience_Level      0
Job_Type              0
Work_Mode             0
Salary_LPA            0
Skills_Required       0
Education_Required    0
Openings              0
Applicants            0
Company_Rating        0
Date_Posted           0
Date_Posted_Month     0
Date_Posted_Year      0
dtype: int64

In [15]:
df.describe()

,Salary_LPA,Openings,Applicants,Company_Rating,Date_Posted_Month,Date_Posted_Year
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,19.829440,3.642600,302.072000,3.698420,6.610200,2024.865400
std,18.136741,4.046942,363.989613,0.424994,3.485669,0.675407
min,0.800000,1.000000,14.000000,2.500000,1.000000,2024.000000
25%,6.800000,1.000000,99.000000,3.400000,3.000000,2024.000000
50%,13.600000,2.000000,185.000000,3.800000,7.000000,2025.000000
75%,25.600000,3.000000,321.000000,4.100000,10.000000,2025.000000
max,115.400000,20.000000,2387.000000,4.300000,12.000000,2026.000000

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df['Salary_LPA'].min()

0.8

In [18]:
df['Salary_LPA'].max()

115.4

In [19]:
bins = [0,10,20,30,40,50,60,70,80,90,120]

labels = [
    "0-10", "10-20", "20-30", "30-40",
    "40-50", "50-60", "60-70", "70-80",
    "80-90", "90-120"
]

df["Salary_LPA_Group"] = pd.cut(
    df["Salary_LPA"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

In [20]:
df.head()

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted,Date_Posted_Month,Date_Posted_Year,Salary_LPA_Group
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025,10,2025,30-40
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025,5,2025,50-60
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024,8,2024,10-20
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026,3,2026,20-30
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024,10,2024,0-10

In [21]:
df['Experience_Level'].unique()

array(['Senior (6-10 yrs)', 'Mid (3-6 yrs)', 'Junior (1-3 yrs)',
       'Fresher (0-1 yr)', 'Lead (10+ yrs)'], dtype=object)

In [22]:
df["Experience_Category"] = df["Experience_Level"].str.extract(r'(^[A-Za-z]+)')

In [23]:
df["Experience_Years"] = df["Experience_Level"].str.extract(r'\((.*?)\)')

In [24]:
df.head()

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,...,Education_Required,Openings,Applicants,Company_Rating,Date_Posted,Date_Posted_Month,Date_Posted_Year,Salary_LPA_Group,Experience_Category,Experience_Years
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,...,M.Tech/M.E.,3,276,4.0,31-10-2025,10,2025,30-40,Senior,6-10 yrs
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,...,B.Tech/B.E.,3,325,4.0,19-05-2025,5,2025,50-60,Senior,6-10 yrs
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,...,MCA,5,559,3.6,21-08-2024,8,2024,10-20,Senior,6-10 yrs
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,...,BCA,3,184,3.5,18-03-2026,3,2026,20-30,Mid,3-6 yrs
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,...,MCA,1,64,3.9,25-10-2024,10,2024,0-10,Junior,1-3 yrs

In [25]:
pd.set_option('display.max_columns', None)

In [26]:
df["Applicants"].min()

14

In [27]:
df["Applicants"].max()

2387

In [28]:
df["Competition_Level"] = pd.cut(
    df["Applicants"],
    bins=[0, 500, 1500, df["Applicants"].max()],
    labels=["Low", "Medium", "High"]
)

In [29]:
df['Skills_Count'] = df["Skills_Required"].str.count(",") + 1

In [30]:
df.head()

,Job_ID,Job_Title,Company,Company_Type,Industry,City,Location_Tier,Experience_Level,Job_Type,Work_Mode,Salary_LPA,Skills_Required,Education_Required,Openings,Applicants,Company_Rating,Date_Posted,Date_Posted_Month,Date_Posted_Year,Salary_LPA_Group,Experience_Category,Experience_Years,Competition_Level,Skills_Count
0,IND2025000,Android Developer,Tech Mahindra,MNC,Information Technology,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,30.9,"Kotlin, Java, REST APIs",M.Tech/M.E.,3,276,4.0,31-10-2025,10,2025,30-40,Senior,6-10 yrs,Low,3
1,IND2025001,QA Engineer,Dream11,Indian Unicorn,Information Technology,Lucknow,Tier 2,Senior (6-10 yrs),Full-Time,Hybrid,58.6,"Selenium, Manual Testing, Postman, API Testing...",B.Tech/B.E.,3,325,4.0,19-05-2025,5,2025,50-60,Senior,6-10 yrs,Low,5
2,IND2025002,Business Analyst,HAL,PSU/Govt,EdTech,Remote,Remote,Senior (6-10 yrs),Full-Time,Remote,18.4,"JIRA, Excel, Power BI",MCA,5,559,3.6,21-08-2024,8,2024,10-20,Senior,6-10 yrs,Medium,3
3,IND2025003,Cybersecurity Analyst,Groww,Startup,Information Technology,Mumbai,Tier 1,Mid (3-6 yrs),Full-Time,Hybrid,21.7,"Penetration Testing, Python, Ethical Hacking, ...",BCA,3,184,3.5,18-03-2026,3,2026,20-30,Mid,3-6 yrs,Low,5
4,IND2025004,Python Developer,Oracle,MNC,EdTech,Remote,Remote,Junior (1-3 yrs),Full-Time,Remote,8.0,"Docker, REST APIs, AWS, PostgreSQL",MCA,1,64,3.9,25-10-2024,10,2024,0-10,Junior,1-3 yrs,Low,4

In [31]:
pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\nayan\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pymysql in c:\users\nayan\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\nayan\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nayan\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [32]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"

raw_password = raw_password = os.getenv("MYSQL_PASSWORD")
password = quote_plus(raw_password)

host = "localhost"
port = "3306"
database = "job_market_db"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

In [33]:
df.to_sql(
    name="job_market_data",
    con=engine,
    if_exists="replace",
    index=False
)

5000

In [34]:
df.shape

(5000, 24)